import os
import re
import subprocess
import time


def derive_project_slug(prompt: str) -> str:
    """Derives a clean kebab-case project and repository slug from the user prompt."""
    m = re.search(r'(?:named?|called)\s+([a-zA-Z0-9_\-]+)', prompt, re.IGNORECASE)
    if m:
        name = m.group(1).lower().replace('_', '-')
        if name not in {'a', 'an', 'the', 'new', 'this', 'my'}:
            return f"{name}-{str(int(time.time()))[-4:]}"

    words = re.findall(r'[a-zA-Z0-9]+', prompt.lower())
    stop_words = {
        'a', 'an', 'the', 'in', 'on', 'at', 'for', 'to', 'of', 'and', 'is', 'it',
        'with', 'write', 'create', 'build', 'make', 'generate', 'please', 'app',
        'application', 'repo', 'repository', 'script', 'code'
    }
    keywords = [w for w in words if w not in stop_words]
    base = '-'.join(keywords[:3]) if keywords else 'agent-app'
    ts = str(int(time.time()))[-4:]
    return f"{base}-{ts}"


def ensure_git_config():
    """Ensures git has an author name and email configured for automated commits."""
    try:
        subprocess.run(["git", "config", "user.name"], check=True, capture_output=True)
    except subprocess.CalledProcessError:
        subprocess.run(["git", "config", "--global", "user.name", "Remote Code Agent"], check=True)
        subprocess.run(["git", "config", "--global", "user.email", "agent@remote-code-agent.local"], check=True)


def publish_project_to_github(project_dir: str, repo_name: str) -> tuple[bool, str]:
    """Initializes git, commits all generated files, and pushes to a new standalone GitHub repository."""
    # Check if there are generated files (excluding hidden files)
    has_files = False
    for root, _, files in os.walk(project_dir):
        if ".git" in root:
            continue
        if any(not f.startswith(".") for f in files):
            has_files = True
            break

    if not has_files:
        return False, "No files were created in the project workspace."

    ensure_git_config()

    # Ensure a README.md exists
    readme_path = os.path.join(project_dir, "README.md")
    if not os.path.exists(readme_path):
        with open(readme_path, "w") as f:
            f.write(f"# {repo_name}\n\nGenerated autonomously by Google Antigravity Remote Code Agent.\n")

    # Initialize git repo in the project directory if not already initialized
    git_dir = os.path.join(project_dir, ".git")
    if not os.path.exists(git_dir):
        subprocess.run(["git", "init", "-b", "main"], cwd=project_dir, check=True, capture_output=True)

    # Commit all files
    subprocess.run(["git", "add", "."], cwd=project_dir, check=True, capture_output=True)
    subprocess.run(
        ["git", "commit", "-m", f"Initial commit: {repo_name} generated by Antigravity Agent"],
        cwd=project_dir,
        capture_output=True,
    )

    # Create and push to GitHub using gh CLI
    remotes = subprocess.run(["git", "remote"], cwd=project_dir, capture_output=True, text=True).stdout
    if "origin" not in remotes:
        res = subprocess.run(
            ["gh", "repo", "create", repo_name, "--public", f"--source={project_dir}", "--remote=origin", "--push"],
            cwd=project_dir,
            capture_output=True,
            text=True,
        )
        if res.returncode == 0:
            url_res = subprocess.run(
                ["gh", "repo", "view", repo_name, "--json", "url", "-q", ".url"],
                cwd=project_dir,
                capture_output=True,
                text=True,
            )
            repo_url = url_res.stdout.strip() or f"https://github.com/noam2030/{repo_name}"
            return True, repo_url
        else:
            return False, f"gh repo create error: {res.stderr.strip()}"
    else:
        res = subprocess.run(["git", "push", "-u", "origin", "main"], cwd=project_dir, capture_output=True, text=True)
        if res.returncode == 0:
            url_res = subprocess.run(
                ["gh", "repo", "view", repo_name, "--json", "url", "-q", ".url"],
                cwd=project_dir,
                capture_output=True,
                text=True,
            )
            repo_url = url_res.stdout.strip() or f"https://github.com/noam2030/{repo_name}"
            return True, repo_url
        else:
            return False, f"git push error: {res.stderr.strip()}"
