import os
import re
import subprocess
import time
from fastapi import Body, FastAPI
from fastapi.responses import StreamingResponse
import google.antigravity
from google.antigravity import Agent, LocalAgentConfig, types
from google.antigravity.hooks import policy

app = FastAPI(title="Google Antigravity Agent Service")

# Dedicated workspace directory for agent-generated projects
BASE_WORKSPACE = os.path.abspath(os.environ.get("AGENT_WORKSPACE", "workspace"))
os.makedirs(BASE_WORKSPACE, exist_ok=True)


def derive_project_slug(prompt: str) -> str:
    """Derives a clean kebab-case project and repository slug from the prompt."""
    m = re.search(r'(?:named?|called)\s+([a-zA-Z0-9_\-]+)', prompt, re.IGNORECASE)
    if m:
        name = m.group(1).lower().replace('_', '-')
        if name not in {'a', 'an', 'the', 'new', 'this', 'my'}:
            return f"{name}-{str(int(time.time()))[-4:]}"

    words = re.findall(r'[a-zA-Z0-9]+', prompt.lower())
    stop_words = {
        'a', 'an', 'the', 'in', 'on', 'at', 'for', 'to', 'of', 'and', 'is', 'it',
        'with', 'write', 'create', 'build', 'make', 'generate', 'please', 'app',
        'application', 'repo', 'repository', 'script', 'code'
    }
    keywords = [w for w in words if w not in stop_words]
    base = '-'.join(keywords[:3]) if keywords else 'agent-app'
    ts = str(int(time.time()))[-4:]
    return f"{base}-{ts}"


def ensure_git_config():
    """Ensures git has an author name and email configured for automated commits."""
    try:
        subprocess.run(["git", "config", "user.name"], check=True, capture_output=True)
    except subprocess.CalledProcessError:
        subprocess.run(["git", "config", "--global", "user.name", "Remote Code Agent"], check=True)
        subprocess.run(["git", "config", "--global", "user.email", "agent@remote-code-agent.local"], check=True)


def publish_project_to_github(project_dir: str, repo_name: str) -> tuple[bool, str]:
    """Initializes git, commits all generated files, and pushes to a new standalone GitHub repository."""
    # Check if there are generated files (excluding hidden files)
    has_files = False
    for root, _, files in os.walk(project_dir):
        if ".git" in root:
            continue
        if any(not f.startswith(".") for f in files):
            has_files = True
            break

    if not has_files:
        return False, "No files were created in the project workspace."

    ensure_git_config()

    # Ensure a README.md exists
    readme_path = os.path.join(project_dir, "README.md")
    if not os.path.exists(readme_path):
        with open(readme_path, "w") as f:
            f.write(f"# {repo_name}\n\nGenerated autonomously by Google Antigravity Remote Code Agent.\n")

    # Initialize git repo in the project directory if not already initialized
    git_dir = os.path.join(project_dir, ".git")
    if not os.path.exists(git_dir):
        subprocess.run(["git", "init", "-b", "main"], cwd=project_dir, check=True, capture_output=True)

    # Commit all files
    subprocess.run(["git", "add", "."], cwd=project_dir, check=True, capture_output=True)
    subprocess.run(
        ["git", "commit", "-m", f"Initial commit: {repo_name} generated by Antigravity Agent"],
        cwd=project_dir,
        capture_output=True,
    )

    # Create and push to GitHub using gh CLI
    remotes = subprocess.run(["git", "remote"], cwd=project_dir, capture_output=True, text=True).stdout
    if "origin" not in remotes:
        res = subprocess.run(
            ["gh", "repo", "create", repo_name, "--public", f"--source={project_dir}", "--remote=origin", "--push"],
            cwd=project_dir,
            capture_output=True,
            text=True,
        )
        if res.returncode == 0:
            url_res = subprocess.run(
                ["gh", "repo", "view", repo_name, "--json", "url", "-q", ".url"],
                cwd=project_dir,
                capture_output=True,
                text=True,
            )
            repo_url = url_res.stdout.strip() or f"https://github.com/noam2030/{repo_name}"
            return True, repo_url
        else:
            return False, f"gh repo create error: {res.stderr.strip()}"
    else:
        res = subprocess.run(["git", "push", "-u", "origin", "main"], cwd=project_dir, capture_output=True, text=True)
        if res.returncode == 0:
            url_res = subprocess.run(
                ["gh", "repo", "view", repo_name, "--json", "url", "-q", ".url"],
                cwd=project_dir,
                capture_output=True,
                text=True,
            )
            repo_url = url_res.stdout.strip() or f"https://github.com/noam2030/{repo_name}"
            return True, repo_url
        else:
            return False, f"git push error: {res.stderr.strip()}"


@app.get("/")
async def root():
    return {
        "status": "online",
        "service": "Google Antigravity Agent Service",
        "docs": "/docs",
        "workspace": BASE_WORKSPACE,
        "github_publishing": "enabled (new standalone repo per app)",
    }


@app.post("/run")
async def run(
    prompt: str = Body(
        ...,
        media_type="text/plain",
        description="Prompt text to send to the Google Antigravity agent",
    )
):
    # Create an isolated project directory for this application
    app_name = derive_project_slug(prompt)
    project_dir = os.path.join(BASE_WORKSPACE, app_name)
    os.makedirs(project_dir, exist_ok=True)

    # Configure agent with the isolated workspace and autonomous permissions
    config = google.antigravity.LocalAgentConfig(
        system_instructions=(
            "You are an expert autonomous software engineer. "
            "Write complete, production-ready code inside your current project workspace. "
            "Always include a detailed README.md explaining the application structure and how to run it. "
            "Ensure all files and dependencies are properly created in your workspace."
        ),
        workspaces=[project_dir],
        policies=[policy.allow_all()],
    )

    async def token_stream():
        async with Agent(config) as agent:
            response = await agent.chat(prompt)

            # Stream real-time chunks (ToolCalls, Thoughts, Text)
            async for chunk in response.chunks:
                if isinstance(chunk, types.Thought):
                    yield f"💭 {chunk.text}"
                elif isinstance(chunk, types.ToolCall):
                    target = (
                        chunk.args.get("file_path")
                        or chunk.args.get("command_line")
                        or chunk.args.get("TargetFile")
                        or chunk.args.get("CommandLine")
                        or ""
                    )
                    detail = f" -> {os.path.basename(target)}" if target else ""
                    yield f"\n⚡ [Tool: {chunk.name}{detail}]\n"
                elif isinstance(chunk, types.Text):
                    yield chunk.text

        # Automatic GitHub Commit & Push after generation completes
        yield f"\n\n📦 [GitHub] Initializing Git repository and publishing to GitHub ({app_name})...\n"
        success, info = publish_project_to_github(project_dir, app_name)
        if success:
            yield (
                f"\n🎉 [GitHub] Successfully pushed code to new repository!\n"
                f"🔗 Repository URL: {info}\n"
                f"📂 Local Path: {project_dir}\n"
            )
        else:
            yield f"\n⚠️ [GitHub Notice] {info}\n"

    headers = {
        "Cache-Control": "no-cache",
        "X-Accel-Buffering": "no",
        "Connection": "keep-alive",
    }
    return StreamingResponse(
        token_stream(), media_type="text/plain", headers=headers
    )
