import os
import re
import subprocess
import time

from remote_code_agent.config import load_env_file

# Ensure .env is loaded if present
load_env_file()


def derive_project_slug(prompt: str) -> str:
    """Derives a clean kebab-case project and repository slug from the user prompt."""
    m = re.search(r'(?:named?|called)\s+([a-zA-Z0-9_\-]+)', prompt, re.IGNORECASE)
    if m:
        name = m.group(1).lower().replace('_', '-')
        if name not in {'a', 'an', 'the', 'new', 'this', 'my'}:
            return f"{name}-{str(int(time.time()))[-4:]}"

    words = re.findall(r'[a-zA-Z0-9]+', prompt.lower())
    stop_words = {
        'a', 'an', 'the', 'in', 'on', 'at', 'for', 'to', 'of', 'and', 'is', 'it',
        'with', 'write', 'create', 'build', 'make', 'generate', 'please', 'app',
        'application', 'repo', 'repository', 'script', 'code'
    }
    keywords = [w for w in words if w not in stop_words]
    base = '-'.join(keywords[:3]) if keywords else 'agent-app'
    ts = str(int(time.time()))[-4:]
    return f"{base}-{ts}"


def get_github_env() -> dict[str, str]:
    """Prepares environment variables for git and gh CLI operations, injecting GH_TOKEN if configured."""
    env = os.environ.copy()
    token = env.get("GH_TOKEN") or env.get("GITHUB_TOKEN")
    if token:
        env["GH_TOKEN"] = token
        env["GITHUB_TOKEN"] = token
    return env


def check_github_auth(env: dict[str, str] | None = None) -> tuple[bool, str]:
    """Validates that GitHub authentication is available via GH_TOKEN/GITHUB_TOKEN or gh CLI status."""
    if env is None:
        env = get_github_env()

    token = env.get("GH_TOKEN") or env.get("GITHUB_TOKEN")
    if token:
        return True, "Authenticated via GH_TOKEN/GITHUB_TOKEN environment variable."

    res = subprocess.run(["gh", "auth", "status"], env=env, capture_output=True, text=True)
    if res.returncode == 0:
        return True, "Authenticated via GitHub CLI."

    return False, (
        "GitHub authentication missing: Neither GH_TOKEN nor GITHUB_TOKEN is set in environment or .env, "
        "and GitHub CLI is not authenticated. Please set GH_TOKEN with 'repo' scope."
    )


def ensure_git_config(env: dict[str, str] | None = None):
    """Ensures git has an author name, email, and credential helper configured for automated commits."""
    if env is None:
        env = get_github_env()
    try:
        subprocess.run(["git", "config", "user.name"], check=True, capture_output=True, env=env)
    except subprocess.CalledProcessError:
        subprocess.run(["git", "config", "--global", "user.name", "Remote Code Agent"], check=True, env=env)
        subprocess.run(["git", "config", "--global", "user.email", "agent@remote-code-agent.local"], check=True, env=env)

    # Setup gh credential helper for git commands
    subprocess.run(["gh", "auth", "setup-git"], check=False, capture_output=True, env=env)


def publish_project_to_github(project_dir: str, repo_name: str) -> tuple[bool, str]:
    """Initializes git, commits all generated files, and pushes to a new standalone GitHub repository."""
    # Check if there are generated files (excluding hidden files)
    has_files = False
    for root, _, files in os.walk(project_dir):
        if ".git" in root:
            continue
        if any(not f.startswith(".") for f in files):
            has_files = True
            break

    if not has_files:
        return False, "No files were created in the project workspace."

    env = get_github_env()
    is_authed, auth_msg = check_github_auth(env)
    if not is_authed:
        return False, auth_msg

    ensure_git_config(env)

    # Ensure a README.md exists
    readme_path = os.path.join(project_dir, "README.md")
    if not os.path.exists(readme_path):
        with open(readme_path, "w") as f:
            f.write(f"# {repo_name}\n\nGenerated autonomously by Google Antigravity Remote Code Agent.\n")

    # Initialize git repo in the project directory if not already initialized
    git_dir = os.path.join(project_dir, ".git")
    if not os.path.exists(git_dir):
        subprocess.run(["git", "init", "-b", "main"], cwd=project_dir, check=True, capture_output=True, env=env)

    # Commit all files
    subprocess.run(["git", "add", "."], cwd=project_dir, check=True, capture_output=True, env=env)
    subprocess.run(
        ["git", "commit", "-m", f"Initial commit: {repo_name} generated by Antigravity Agent"],
        cwd=project_dir,
        capture_output=True,
        env=env,
    )

    # Resolve default owner URL fallback
    owner_res = subprocess.run(["gh", "api", "user", "-q", ".login"], cwd=project_dir, capture_output=True, text=True, env=env)
    owner = owner_res.stdout.strip() if owner_res.returncode == 0 and owner_res.stdout.strip() else "noam2030"

    # Create and push to GitHub using gh CLI
    remotes = subprocess.run(["git", "remote"], cwd=project_dir, capture_output=True, text=True, env=env).stdout
    if "origin" not in remotes:
        res = subprocess.run(
            ["gh", "repo", "create", repo_name, "--public", f"--source={project_dir}", "--remote=origin", "--push"],
            cwd=project_dir,
            capture_output=True,
            text=True,
            env=env,
        )
        if res.returncode == 0:
            url_res = subprocess.run(
                ["gh", "repo", "view", repo_name, "--json", "url", "-q", ".url"],
                cwd=project_dir,
                capture_output=True,
                text=True,
                env=env,
            )
            repo_url = url_res.stdout.strip() or f"https://github.com/{owner}/{repo_name}"
            return True, repo_url
        else:
            return False, f"gh repo create error: {res.stderr.strip()}"
    else:
        res = subprocess.run(["git", "push", "-u", "origin", "main"], cwd=project_dir, capture_output=True, text=True, env=env)
        if res.returncode == 0:
            url_res = subprocess.run(
                ["gh", "repo", "view", repo_name, "--json", "url", "-q", ".url"],
                cwd=project_dir,
                capture_output=True,
                text=True,
                env=env,
            )
            repo_url = url_res.stdout.strip() or f"https://github.com/{owner}/{repo_name}"
            return True, repo_url
        else:
            return False, f"git push error: {res.stderr.strip()}"
